name: xeus-cling
channels:
  - conda-forge
dependencies:
  - xeus-cling
  - xeus-python
  - matplotlib-base
  - notebook < 7.0
  - pip:
    - rise
    - nbgitpuller
    - jupyter-contrib-nbextensions
